# Generated by Django 5.2.1 on 2025-05-20 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_rag', models.BooleanField(default=False)),
                ('model_data', models.JSONField()),
                ('response_time', models.FloatField()),
                ('log_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '聊天记录',
                'verbose_name_plural': '聊天记录',
                'db_table': 'chat_log',
                'ordering': ['-log_time'],
            },
        ),
    ]
